version: '3.3'

services:
  mysql_barka_db:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_DATABASE: 'barka_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql