version: '3.1'

services:

  barka-sqlserver:
    container_name: barka-mssqlserver-db
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "Th1s1sMyPass_word"
        ACCEPT_EULA: "Y"
    healthcheck:
      test: sqlcmd -S localhost -U sa -P 'Th1s1sMyPass_word' -Q 'SELECT GETDATE()'
    volumes:
      - ./mssql/data:/var/opt/mssql/data

  devtools:
    container_name: msft-dev-tools
    image: mcr.microsoft.com/mssql-tools:latest
    environment:
      SA_PASSWORD: "Th1s1sMyPass_word"
      ACCEPT_EULA: "Y"
    command: [ "./var/opt/scripts/wait_for_it.sh", "localhost:1433", "--", "bash", "/var/opt/scripts/db_setup.sh" ]
    volumes:
      - ./scripts:/var/opt/scripts
    depends_on:
      - mssqlserver